grails-app/domain/seguridad/Usuario.groovy
package seguridad

import Maestros.MaestroCliente;
import Maestros.MaestroPlanta;

class Usuario 
{
	transient springSecurityService

	String username
	String password
	boolean estado = true
	boolean accountExpired
	boolean accountLocked
	boolean passwordExpired
	
	String nombre
	String apellido	
	
	static belongsTo = [cliente:MaestroCliente]
	
	static hasMany = [permisos:UsuarioPermiso]
		
	def cliente() { cliente?.razonSocial }
	
	static transients = ['springSecurityService']
	
	static constraints = 
	{
		nombre (blank:false,size:1..150)
		apellido(blank:false,size:1..150)		
		username (blank: false, unique: true)
		password (blank: false)		
	}

	static mapping = 
	{
		password column: '`password`'
		datasource 'DEFAULT'		
	}

	Set<Permiso> getAuthorities() { UsuarioPermiso.findAllByUsuario(this).collect { it.permiso } }

	def beforeInsert() { encodePassword() }

	def beforeUpdate() { if (isDirty('password')) { encodePassword() } }

	protected void encodePassword() { password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password }
	
	String toString() { return "$username" }
}

grails-app/controllers/seguridad/UsuarioController.groovy
package seguridad

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import Maestros.MaestroCliente

@Transactional(readOnly = true)
class UsuarioController 
{
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) 
	{
        params.max = 10
		
		def cliente = MaestroCliente.get(params.cliente)
		
		def usuarios = Usuario.createCriteria().list(params)
		{
			if(params.nombre) { ilike('nombre', '%' + params.nombre + '%') }
			if(params.apellido) { ilike('apellido', '%' + params.apellido + '%') }
			if(params.username) { ilike('username', '%' + params.username + '%') }
			if(cliente) { eq('cliente', cliente) }
			if(params.activo == 'Si') { eq('accountLocked', false) } else if(params.activo == 'No') { eq('accountLocked', true) }
		}
		
        model:[usuarios:usuarios]
    }

    def show(Usuario usuario) { model:[usuario:usuario] }

    def create() { respond new Usuario(params) }

    @Transactional
    def save(Usuario usuario) 
	{
        usuario.save flush:true, failOnError:true

        flash.message = "El Usuario se ha guardado exitosamente."
        redirect usuario
    }

    def edit(Usuario usuario) { respond usuario }

    @Transactional
    def update(Usuario usuario) 
	{
        usuario.save flush:true, failOnError:true

        flash.message = "El Usuario se ha actualizado exitosamente."
        redirect usuario
    }

    @Transactional
    def delete(Usuario usuario) 
	{
        usuario.accountLocked = !usuario.accountLocked

		if(usuario.accountLocked) { flash.message = "El usuario se ha desactivado exitosamente." } else { flash.message = "El usuario se ha activado exitosamente." }
		
        redirect usuario
    }
}

grails-app/views/usuario/_form.gsp
<%@ page import = "seguridad.Usuario" %>

<div class = "fieldcontain">
	
	<label for = "username"> Username <span class = "required-indicator">*</span> </label> <g:textField name = "username" required = "" value = "${usuarioInstance?.username}"/>

</div>

<div class = "fieldcontain">

	<label for = "password"> Contraseña <span class = "required-indicator">*</span> </label> <g:textField name = "password" required = "" value = "${usuarioInstance?.password}"/>

</div>

<div class = "fieldcontain">
	
	<label for = "nombre"> Nombre <span class="required-indicator">*</span> </label> <g:textField name = "nombre" maxlength = "150" required = "" value = "${usuarioInstance?.nombre}"/>

</div>

<div class = "fieldcontain">

	<label for = "apellido"> Apellido <span class = "required-indicator">*</span> </label> <g:textField name = "apellido" maxlength = "150" required = "" value = "${usuarioInstance?.apellido}"/>

</div>

<div class = "fieldcontain">
	
	<label for = "cliente"> Cliente <span class = "required-indicator">*</span> </label> 
	
	<g:select name = "cliente.id" from = "${Maestros.MaestroCliente.list()}" optionKey = "id" required = "" value = "${usuarioInstance?.cliente?.id}" />

</div>

grails-app/views/usuario/create.gsp
<!DOCTYPE html>

<html>

	<head> <meta name = "layout" content = "main"> <title> Creando Usuario </title> </head>
	
	<body>
	
		<div class = "nav" role = "navigation"> <ul> <li> <g:link class = "list" action = "index"> Listado de Usuarios </g:link> </li> </ul> </div>
		
		<div class = "content scaffold-create" role = "main">
			
			<br/> <g:if test = "${flash.message}"> <div class = "message" role = "status"> ${flash.message} </div> </g:if>
			
			<h1> Creando Usuario </h1>
			
			<g:form resource = "${usuarioInstance}" action = "save" >
			
				<fieldset class = "form"> <g:render template = "form"/> </fieldset>
				
				<fieldset class = "buttons"> <g:submitButton name = "create" class = "save" value = "Crear" /> </fieldset>
				
			</g:form>
			
		</div>
		
	</body>
	
</html>

grails-app/views/usuario/edit.gsp
<%@ page import = "seguridad.Usuario" %>

<!DOCTYPE html>

<html>

	<head> <meta name = "layout" content = "main"> <title> Editando Usuario </title> </head>
	
	<body>
	
		<div class = "nav" role = "navigation">
			
			<ul>
				<li> <g:link class = "list" action = "index"> Listado de Usuarios </g:link> </li>
				<li> <g:link class = "create" action = "create"> Crear Usuario </g:link> </li>
			</ul>
			
		</div>
		
		<div class = "content scaffold-edit" role = "main">
			
			<br/> <g:if test = "${flash.message}"> <div class = "message" role = "status"> ${flash.message} </div> </g:if>
			
			<h1> Editando Usuario </h1>
			
			<g:form resource = "${usuarioInstance}" action = "update" method = "PUT" >
				
				<g:hiddenField name = "version" value = "${usuarioInstance?.version}" />
				
				<fieldset class = "form"> <g:render template = "form"/> </fieldset>
				
				<fieldset class = "buttons"> <g:actionSubmit class = "save" action = "update" value = "Actualizar" /> </fieldset>
				
			</g:form>
			
		</div>
		
	</body>
	
</html>

grails-app/views/usuario/index.gsp
<%@ page import = "seguridad.Usuario" %>

<!DOCTYPE html>

<html>

	<head> <meta name = "layout" content = "main"> <title> Listado de Usuarios </title> </head>
	
	<body>
	
		<div class = "nav" role = "navigation"> <ul> <li> <g:link class = "create" action = "create"> Crear Usuario </g:link> </li> </ul> </div>
		
		<div class = "content scaffold-list" role = "main">
		
			<br/> <g:if test = "${flash.message}"> <div class = "message" role = "status"> ${flash.message} </div> </g:if>
			
			<g:form action = "index">
			
				<h1> Listado de Usuarios </h1> <br/>
				
				<table style = "margin-left: 2.5%">
					
					<thead> <tr> <th> Username </th> <th> Nombre </th> <th> Apellido </th> <th> Cliente </th> <th> Activo </th> </tr> </thead>
					
					<tbody>
						
						<tr class = "noclass">
						 
							<td> <input name = "username" value = "${params.username}" />  </td>
							<td> <input name = "nombre" value = "${params.nombre}" /> </td>
							<td> <input name = "apellido" value = "${params.apellido}" /> </td>
							<td> <g:select name = "cliente" from = "${Maestros.MaestroCliente.list().sort { it.razonSocial }}" noSelection = "['':'Seleccione']" optionKey = "id" value = "${params.cliente}"/> </td>
							<td> <g:select name = "activo" from = "${['Si', 'No']}" noSelection = "['':'Seleccione']" value = "${params.activo}"/> </td>
						
						</tr>
						
						<g:each in = "${usuarios}" status = "i" var = "usuario">
							
							<tr class = "${(i % 2) == 0 ? 'even' : 'odd'}">
							
								<td> <g:link action = "show" id = "${usuario.id}"> ${usuario.username} </g:link> </td>
								
								<td> ${usuario.nombre} </td> <td> ${usuario.apellido}</td> <td> ${usuario.cliente}</td>
							
								<td> <g:formatBoolean boolean = "${usuario.accountLocked}" false = "Si" true = "No"/> </td>
							
							</tr>
							
						</g:each>
						
					</tbody>
					
				</table>
				
				<div class = "paginations"> <g:submitButton name = "Filtrar" class = "botonBuscador"/> <g:paginate total = "${usuarios.totalCount ?: 0}" /> </div>
			
			</g:form>
			
		</div>
		
	</body>
	
</html>

grails-app/views/usuario/show.gsp
<%@ page import = "seguridad.Usuario" %>

<!DOCTYPE html>

<html>
	
	<head> <meta name = "layout" content = "main"> <title> Mostrando Usuario </title> </head>
	
	<body>
	
		<div class = "nav" role = "navigation">
		
			<ul>			
				<li> <g:link class = "list" action = "index"> Listado de Usuarios </g:link> </li>
				<li> <g:link class = "create" action = "create"> Crear Usuario </g:link> </li>
			</ul>
			
		</div>
		
		<div class = "content scaffold-show" role = "main">
			
			<br/> <g:if test = "${flash.message}"> <div class = "message" role = "status"> ${flash.message} </div> </g:if>
			
			<h1> Mostrando Usuario </h1>
			
			<ol class = "property-list usuario">
			
				<li class = "fieldcontain"> <span class = "property-label"> Nombre </span> <span class = "property-value"> ${usuario.nombre} </span> </li>

				<li class = "fieldcontain"> <span class = "property-label"> Apellido </span> <span class = "property-value"> ${usuario.apellido} </span> </li>

				<li class = "fieldcontain"> <span class = "property-label"> Username </span> <span class = "property-value"> ${usuario.username} </span> </li>
		
				<li class = "fieldcontain"> <span class = "property-label"> Cliente </span> <span class = "property-value"> ${usuario?.cliente} </span> </li>
		
				<li class = "fieldcontain"> 
					
					<span class = "property-label"> Activo </span> 
					
					<span class = "property-value"> <g:formatBoolean boolean = "${usuario?.accountLocked}" false = "Si" true = "No" /> </span>
					
				</li>

			</ol>
			
			<g:form resource = "${usuario}" action = "delete" method = "DELETE">
				
				<fieldset class = "buttons">
				
					<g:link class = "edit" action = "edit" resource = "${usuario}"> Editar </g:link>
					
					<g:if test = "${!usuario.accountLocked}"> 
						
						<input class = "delete" id = "eliminar" value = "Desactivar" type = "submit" >
					
						<script>
	
							$(document).ready(function(){ $('#eliminar').on('click', function(e){ e.preventDefault(); bootbox.confirm("¿Esta seguro de desactivar el Usuario?", 
							function(confirmed) { if(confirmed == true) { $(document).ready(function(){$('#eliminarFinal').trigger('click'); }); } });  }); });
				
						</script>
						
						<div hidden = ""> <input id = "eliminarFinal" type = "submit" name = "accion" value = "Desactivar"> </div>
					
					</g:if>
					
					<g:else>
						
						<input class = "add" id = "activar" value = "Activar" type = "submit" >
						
						<script>
							
							$(document).ready(function(){ $('#activar').on('click', function(e){ e.preventDefault(); bootbox.confirm("¿Esta seguro de activar el Usuario?", 
							function(confirmed) { if(confirmed == true) { $(document).ready(function(){$('#activarFinal').trigger('click'); }); } });  }); });
						
						</script>
						
						<div hidden = ""> <input id = "activarFinal" type = "submit" name = "accion" value = "Activar"> </div>
					
					</g:else>
					
				</fieldset>
				
			</g:form>
			
		</div>
		
	</body>
	
</html>