grails-app/domain/transaccionales/EnvioCorreo.groovy
package transaccionales

class EnvioCorreo 
{
	Date fechaEnvio
	String numeroCamion
	Integer tipoInspeccion

    static constraints = {  }
}

grails-app/controllers/transaccionales/EnvioCorreoController.groovy
package transaccionales

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import jxl.Workbook
import jxl.write.Label
import jxl.write.WritableSheet
import jxl.write.WritableWorkbook
import Maestros.MaestroTipoInspeccion

@Transactional(readOnly = true)
class EnvioCorreoController 
{
    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index() 
	{
        def correosEnviados = EnvioCorreo.findAllByFechaEnvioBetween(params.fechaInicio, params.fechaFinal)
		
		if(correosEnviados)
		{
			String nombre = "Correos_Enviados.xls"
			response.setContentType('application/vnd.ms-excel')
			response.setHeader('Content-Disposition', 'Attachment;Filename=' + nombre)
			WritableWorkbook workbook = Workbook.createWorkbook(response.outputStream)
			
			WritableSheet sheet1 = workbook.createSheet("Hoja1", 0)
			
			sheet1.setColumnView(0, 20)
			sheet1.setColumnView(1, 20)
			sheet1.setColumnView(2, 30)
			
			sheet1.addCell(new Label(0, 0, "Fecha Envio"))
			sheet1.addCell(new Label(1, 0, "Numero Camion"))
			sheet1.addCell(new Label(2, 0, "Tipo de Inspeccion"))
					
			correosEnviados.eachWithIndex
			{
				correo, i ->
				
				def tipoIns = MaestroTipoInspeccion.get(correo.tipoInspeccion).descripcion
				
				sheet1.addCell(new Label(0, 2 + i, g.formatDate(date:correo.fechaEnvio, format:'dd-MM-yyyy')))
				sheet1.addCell(new Label(1, 2 + i, correo.numeroCamion))
				sheet1.addCell(new Label(2, 2 + i, tipoIns))				
			}
			
			workbook.write()
			workbook.close()
			
			flash.message = "Se ha(n) encontrado ${correosEnviados.size} dato(s)."
		}
		else { flash.warning = "No se han encontrado datos para los parametros seleccionados." }
    }
}

grails-app/views/envioCorreo/index.gsp
<%@ page import="transaccionales.EnvioCorreo" %>

<!DOCTYPE html>

<html>

	<head> <meta name = "layout" content = "main"> <title> Envío de Correo </title> </head>
	
	<body>
	
		<div id = "list-envioCorreo" class = "content scaffold-list" role = "main">
			
			<br/> <g:if test = "${flash.message}"> <div class = "message" role = "status"> ${flash.message} </div> </g:if> 
			<g:elseif test = "${flash.warning}"> <div class = "errors"> ${flash.warning} </div> </g:elseif> 
			
			<h1> Registro de Correos Enviados </h1> <br/>
			
			<table style = "margin-left: 2.5%; width:95%" class = "buttons"> 
			
				<tbody>  	 
  		  			
  		  			<g:form action = "index">
  		  				
						<tr class = "noclass">
		  	  											
							<td> Fecha Inicio: </td> 
							
							<td> <g:datePicker name = "fechaInicio" value = "${new Date()}" precision = "day" years = "${new Date()[Calendar.YEAR] - 5..new Date()[Calendar.YEAR]}"/> </td>
							
							<td> Fecha Final: </td> 
							
							<td> <g:datePicker name = "fechaFinal" value = "${new Date()}" precision = "day" years = "${new Date()[Calendar.YEAR] - 5..new Date()[Calendar.YEAR]}"/> </td>
							
							<td> <input id = "env" class = "botonGuardarPersonalizado" type = "submit" value = "Enviar"> </td>
							
						</tr>
						
					</g:form>
				
				</tbody>
				
			</table>
			
			<div class = "pagination"> <g:paginate total="${envioCorreoInstanceCount ?: 0}" /> </div>
			
		</div>
		
	</body>
	
</html>