grails-app/domain/seguridad/UsuarioPermiso.groovy
package seguridad

import org.apache.commons.lang.builder.HashCodeBuilder

class UsuarioPermiso implements Serializable 
{
	private static final long serialVersionUID = 1

	Usuario usuario
	Permiso permiso

	boolean equals(other) 
	{
		if (!(other instanceof UsuarioPermiso)) { return false }

		other.usuario?.id == usuario?.id &&
		other.permiso?.id == permiso?.id
	}

	int hashCode() 
	{
		def builder = new HashCodeBuilder()
		if (usuario) builder.append(usuario.id)
		if (permiso) builder.append(permiso.id)
		builder.toHashCode()
	}

	static UsuarioPermiso get(long usuarioId, long permisoId) 
	{
		UsuarioPermiso.where {
			usuario == Usuario.load(usuarioId) &&
			permiso == Permiso.load(permisoId)
		}.get()
	}

	static boolean exists(long usuarioId, long permisoId) 
	{
		UsuarioPermiso.where {
			usuario == Usuario.load(usuarioId) &&
			permiso == Permiso.load(permisoId)
		}.count() > 0
	}

	static UsuarioPermiso create(Usuario usuario, Permiso permiso, boolean flush = false) {
		def instance = new UsuarioPermiso(usuario: usuario, permiso: permiso)
		instance.save(flush: flush, insert: true)
		instance
	}

	static boolean remove(Usuario u, Permiso r, boolean flush = false) {
		if (u == null || r == null) return false

		int rowCount = UsuarioPermiso.where {
			usuario == Usuario.load(u.id) &&
			permiso == Permiso.load(r.id)
		}.deleteAll()

		if (flush) { UsuarioPermiso.withSession { it.flush() } }

		rowCount > 0
	}

	static void removeAll(Usuario u, boolean flush = false) {
		if (u == null) return

		UsuarioPermiso.where {
			usuario == Usuario.load(u.id)
		}.deleteAll()

		if (flush) { UsuarioPermiso.withSession { it.flush() } }
	}

	static void removeAll(Permiso r, boolean flush = false) {
		if (r == null) return

		UsuarioPermiso.where {
			permiso == Permiso.load(r.id)
		}.deleteAll()

		if (flush) { UsuarioPermiso.withSession { it.flush() } }
	}

	static constraints = 
	{
		permiso validator: { Permiso r, UsuarioPermiso ur ->
			if (ur.usuario == null) return
			boolean existing = false
			UsuarioPermiso.withNewSession {
				existing = UsuarioPermiso.exists(ur.usuario.id, r.id)
			}
			if (existing) {
				return 'userRole.exists'
			}
		}
	}

	static mapping = {
		id composite: ['permiso', 'usuario']
		version false
	}
}

grails-app/controllers/seguridad/UsuarioPermisoController.groovy
package seguridad

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class UsuarioPermisoController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) 
	{
        params.max = 10
        
		def asociaciones = UsuarioPermiso.createCriteria().list(params) 
		{
			if(params.usuario) { usuario { ilike('username', '%' + params.usuario + '%') } }
			if(params.permiso) { permiso { ilike('authority', '%' + params.permiso + '%') } }
		}
		
		model:[asociaciones:asociaciones]
    }

    def show(UsuarioPermiso asociacion) { model:[asociacion:asociacion] }

    def create() { model:[asociacion:new UsuarioPermiso(params)] }

    @Transactional
    def save(UsuarioPermiso asociacion) 
	{        
        asociacion.save flush:true, failOnError:true

        flash.message = "La asociacion se ha creado exitosamente."
        redirect action:"index", method:"GET"
    }

    @Transactional
    def delete(UsuarioPermiso asociacion) 
	{        
		asociacion.delete flush:true, failOnError:true

        flash.message = "La asociacion se ha eliminado exitosamente."
        redirect action:"index", method:"GET"
    }
}

grails-app/views/usuarioPermiso/_form.gsp
<%@ page import = "seguridad.UsuarioPermiso" %>

<div class = "fieldcontain required">

	<label for = "permiso"> Permiso <span class = "required-indicator">*</span> </label>
	
	<g:select name = "permiso.id" from = "${seguridad.Permiso.list()}" optionKey = "id" required = "" value = "${usuarioPermisoInstance?.permiso?.id}" />

</div>

<div class = "fieldcontain required">
	
	<label for = "usuario"> Usuario <span class = "required-indicator">*</span> </label>
	
	<g:select name = "usuario.id" from = "${seguridad.Usuario.list()}" optionKey = "id" required = "" value = "${usuarioPermisoInstance?.usuario?.id}" />

</div>

grails-app/views/usuarioPermiso/create.gsp
<!DOCTYPE html>

<html>

	<head> <meta name = "layout" content = "main"> <title> Crear Asociación </title> </head>
	
	<body>
	
		<div class = "nav" role = "navigation"> <ul> <li> <g:link class = "list" action = "index"> Listado de Asociaciones </g:link> </li> </ul> </div>
		
		<div class = "content scaffold-create" role = "main">
			
			<br/> <g:if test = "${flash.message}"> <div class = "message" role = "status"> ${flash.message} </div> </g:if>
			
			<h1> Creando Usuario Permiso </h1> 
			
			<g:form url = "[resource:usuarioPermisoInstance, action:'save']" >
				
				<fieldset class = "form"> <g:render template = "form"/> </fieldset> <fieldset class = "buttons"> <g:submitButton name = "create" class = "save" value = "Crear" /> </fieldset>
				
			</g:form>
			
		</div>
		
	</body>
	
</html>

grails-app/views/usuarioPermiso/index.gsp
<%@ page import = "seguridad.UsuarioPermiso" %>

<!DOCTYPE html>

<html>

	<head> <meta name = "layout" content = "main"> <title> Listado de Asociaciones </title> </head>
	
	<body>
	
		<div class = "nav" role = "navigation"> <ul> <li> <g:link class = "create" action = "create"> Crear Asociación </g:link> </li> </ul> </div>
		
		<div class = "content scaffold-list" role = "main">
			
			<br/> <g:if test = "${flash.message}"> <div class = "message" role = "status"> ${flash.message} </div> </g:if>
			
			<h1> Listado de Usuarios Permiso </h1> <br/> 
			
			<g:form action = "index">
			
				<table style = "margin-left: 2.5%">
					
					<thead> <tr> <th> Permiso </th> <th> Usuario </th> </tr> </thead>
					
					<tbody>
						
						<tr class = "noclass"> <td> <input name = "permiso" value = "${params.permiso}" /> </td> <td> <input name = "usuario" value = "${params.usuario}" /> </td> </tr>
						
						<g:each in = "${asociaciones}" status = "i" var = "asociacion">
						
							<tr class = "${(i % 2) == 0 ? 'even' : 'odd'}">
						
								<td> ${asociacion.permiso} </td> <td> ${asociacion.usuario} </td>
						
							</tr>
							
						</g:each>
						
					</tbody>
					
				</table>
				
				<div class = "paginations"> <g:submitButton class = "botonBuscador" name = "Buscar"/> <g:paginate total = "${asociaciones.totalCount ?: 0}" /> </div>
				
			</g:form>
			
		</div>
		
	</body>
	
</html>